
const data = [
{"id": 1, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:843769/ada?", "title":"Gender Queer", "author":"Maia Kobabe", "ibsn":9781549304002,"image":"", "description":"In 2014, Maia Kobabe, who uses e/em/eir pronouns, thought that a comic of reading statistics would be the last autobiographical comic e would ever write. At the time, it was the only thing e felt comfortable with strangers knowing about em. Now, Gender Queer is here. Maia's intensely cathartic autobiography charts eir journey of self-identity, which includes the mortification and confusion of adolescent crushes, grappling with how to come out to family and society, bonding with friends over erotic gay fanfiction, and facing the trauma and fundamental violation of pap smears. Started as a way to explain to eir family what it means to be nonbinary and asexual, Gender Queer is more than a personal story: it is a useful and touching guide on gender identity--what it means and how to think about it--for advocates, friends, and humans everywhere.", "reasons":"Banned, challenged, and restricted for LGBTQIA+ content, and because it was considered to have sexually explicit images"},
{"id": 2, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:794588/one?", "title":"Lawn Boy", "author":"Jonathan Evison", "ibsn":978161620262097816162,"image":"", "description":"Mike Muñoz is a young Mexican American not too many years out of high school--and just fired from his latest gig as a lawn boy on a landscaping crew. Though he tries time and again to get his foot on the first rung of that ladder to success, he can't seem to get a break. But then things start to change for Mike, and after a raucous, jarring, and challenging trip, he finds he can finally see the future and his place in it", "reasons":"Banned and challenged for LGBTQIA+ content and because it was considered to be sexually explicit"},
{"id": 3, "link" : "", "title":"All Boys Aren't Blue", "author":"George M. Johnson", "ibsn":"","image":"", "description":"", "reasons":"Banned and challenged for LGBTQIA+ content, profanity, and because it was considered to be sexually explicit"},
{"id": 4, "link" : "", "title":"Out of Darkness", "author":"Ashley Hope Perez", "ibsn":"","image":"", "description":"", "reasons":"Banned, challenged, and restricted for depictions of abuse and because it was considered to be sexually explicit"},
{"id": 5, "link" : "", "title":"The Hate U Give", "author":"Angie Thomas", "ibsn":"","image":"", "description":"", "reasons":"Banned and challenged for profanity, violence, and because it was thought to promote an anti-police message and indoctrination of a social agenda"},
{"id": 6, "link" : "", "title":"The Absolutely True Diary of a Part-Time Indian", "author":"Sherman Alexie", "ibsn":"","image":"", "description":"", "reasons":"Banned and challenged for profanity, sexual references and use of a derogatory term"},
{"id": 7, "link" : "", "title":"Me and Earl and the Dying Girl ", "author":"Jesse Andrews", "ibsn":"","image":"", "description":"", "reasons":"Banned and challenged because it was considered sexually explicit and degrading to women"},
{"id": 8, "link" : "", "title":"The Bluest Eye", "author":"Toni Morrison", "ibsn":"","image":"", "description":"", "reasons":"Banned and challenged because it depicts child sexual abuse and was considered sexually explicit"},
{"id": 9, "link" : "", "title":"This Book is Gay", "author":"Juno Dawson", "ibsn":"","image":"", "description":"", "reasons":"Banned, challenged, relocated, and restricted for providing sexual education and LGBTQIA+ content."},
{"id": 10, "link" : "", "title":"Beyond Magenta ", "author":"Susan Kuklin", "ibsn":"","image":"", "description":"", "reasons":"Banned and challenged for LGBTQIA+ content and because it was considered to be sexually explicit. "},
];

export default data;