import genderQueerImage from './images/9781549304002.jpeg';
import lawnBoyImage from './images/9781616202620.jpeg';
import allBoysImage from './images/9780374312718.jpeg';
import outOfDarkImage from './images/9781467742023.jpeg';
import theHateImage from './images/9780062498533.jpeg';
import theAbsoluteImage from './images/9780316013697.jpeg';
import meAndEarlImage from './images/9781419701764.jpeg';
import theBluestImage from './images/9780375411557.jpeg';
import thisBookImage from './images/9781492617822.jpeg';
import beyondMagentaImage from './images/9780763656119.jpeg';

const data = [
{"id": 1, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:843769/ada?", "title":"Gender Queer", "author":"Maia Kobabe", "ibsn":9781549304002,"image":genderQueerImage, "description":"In 2014, Maia Kobabe, who uses e/em/eir pronouns, thought that a comic of reading statistics would be the last autobiographical comic e would ever write. At the time, it was the only thing e felt comfortable with strangers knowing about em. Now, Gender Queer is here. Maia's intensely cathartic autobiography charts eir journey of self-identity, which includes the mortification and confusion of adolescent crushes, grappling with how to come out to family and society, bonding with friends over erotic gay fanfiction, and facing the trauma and fundamental violation of pap smears. Started as a way to explain to eir family what it means to be nonbinary and asexual, Gender Queer is more than a personal story: it is a useful and touching guide on gender identity--what it means and how to think about it--for advocates, friends, and humans everywhere.", "reasons":"Banned, challenged, and restricted for LGBTQIA+ content, and because it was considered to have sexually explicit images"},
{"id": 2, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:794588/one?", "title":"Lawn Boy", "author":"Jonathan Evison", "ibsn":978161620262097816162,"image":lawnBoyImage, "description":"Mike Muñoz is a young Mexican American not too many years out of high school--and just fired from his latest gig as a lawn boy on a landscaping crew. Though he tries time and again to get his foot on the first rung of that ladder to success, he can't seem to get a break. But then things start to change for Mike, and after a raucous, jarring, and challenging trip, he finds he can finally see the future and his place in it", "reasons":"Banned and challenged for LGBTQIA+ content and because it was considered to be sexually explicit"},
{"id": 3, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:863562/ada?", "title":"All Boys Aren't Blue", "author":"George M. Johnson", "ibsn":9780374312718,"image":allBoysImage, "description":"In a series of personal essays, prominent journalist and LGBTQIA+ activist George M. Johnson explores his childhood, adolescence, and college years in New Jersey and Virginia. From the memories of getting his teeth kicked out by bullies at age five, to flea marketing with his loving grandmother, to his first sexual relationships, this young-adult memoir weaves together the trials and triumphs faced by Black queer boys.", "reasons":"Banned and challenged for LGBTQIA+ content, profanity, and because it was considered to be sexually explicit"},
{"id": 4, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:717458/ada?", "title":"Out of Darkness", "author":"Ashley Hope Perez", "ibsn":9781467742023,"image":outOfDarkImage, "description":"Loosely based on a school explosion that took place in New London, Texas in 1937, this is the story of two teenagers: Naomi, who is Mexican, and Wash, who is black, and their dealings with race, segregation, love, and the forces that destroy people", "reasons":"Banned, challenged, and restricted for depictions of abuse and because it was considered to be sexually explicit"},
{"id": 5, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:765617/ada?", "title":"The Hate U Give", "author":"Angie Thomas", "ibsn":9780062498533,"image":theHateImage, "description":"After witnessing her friend's death at the hands of a police officer, Starr Carter's life is complicated when the police and a local drug lord try to intimidate her in an effort to learn what happened the night Kahlil died.", "reasons":"Banned and challenged for profanity, violence, and because it was thought to promote an anti-police message and indoctrination of a social agenda"},
{"id": 6, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:532690/ada?", "title":"The Absolutely True Diary of a Part-Time Indian", "author":"Sherman Alexie", "ibsn":9780316013697,"image":theAbsoluteImage, "description":"Budding cartoonist Junior leaves his troubled school on the Spokane Indian Reservation to attend an all-white farm town school where the only other Indian is the school mascot.", "reasons":"Banned and challenged for profanity, sexual references and use of a derogatory term"},
{"id": 7, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:588400/ada?", "title":"Me and Earl and the Dying Girl", "author":"Jesse Andrews", "ibsn":9781419701764,"image":meAndEarlImage, "description":"Seventeen-year-old Greg has managed to become part of every social group at his Pittsburgh high school without having any friends, but his life changes when his mother forces him to befriend Rachel, a girl he once knew in Hebrew school who has leukemia.", "reasons":"Banned and challenged because it was considered sexually explicit and degrading to women"},
{"id": 8, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:217111/ada?", "title":"The Bluest Eye", "author":"Toni Morrison", "ibsn":9780375411557,"image":theBluestImage, "description":"The Bluest Eye, published in 1970, is the first novel written by Toni Morrison, winner of the 1993 Nobel Prize in Literature. It is the story of eleven-year-old Pecola Breedlove - a black girl in an America whose love for its blond, blue-eyed children can devastate all others - who prays for her eyes to turn blue: so that she will be beautiful, so that people will look at her, so that her world will be different. This is the story of the nightmare at the heart of her yearning and the tragedy of its fulfillment.", "reasons":"Banned and challenged because it depicts child sexual abuse and was considered sexually explicit"},
{"id": 9, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:710767/ada?", "title":"This Book is Gay", "author":"Juno Dawson", "ibsn":9781492617822,"image":thisBookImage, "description":"esbian. Bisexual. Queer. Transgender. Striaght. Curious. This book is for everyone, regardless of gender or sexual preference. This book is for anyone who's ever dared to wonder", "reasons":"Banned, challenged, relocated, and restricted for providing sexual education and LGBTQIA+ content."},
{"id": 10, "link" : "https://mtpros.ent.sirsi.net/client/en_US/default/search/detailnonmodal/ent:$002f$002fSD_ILS$002f0$002fSD_ILS:656667/ada?", "title":"Beyond Magenta", "author":"Susan Kuklin", "ibsn":9780763656119,"image":beyondMagentaImage, "description":"Author and photographer Susan Kuklin met and interviewed six transgender or gender-neutral young adults and used her considerable skills to represent them thoughtfully and respectfully before, during, and after their personal acknowledgment of gender preference. Portraits, family photographs, and candid images grace the pages, augmenting the emotional and physical journey each youth has taken. Each honest discussion and disclosure, whether joyful or heartbreaking, is completely different from the other because of family dynamics, living situations, gender, and the transition these teens make in recognition of their true selves.", "reasons":"Banned and challenged for LGBTQIA+ content and because it was considered to be sexually explicit. "},
];

export default data;